// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_LJdQO2rOqtlhP2yAdESC1PY1uvyJiE',
    appId: '1:263563615046:web:667b213785e5a0b7356347',
    messagingSenderId: '263563615046',
    projectId: 'whatsapp-stickers-app-7de9f',
    authDomain: 'whatsapp-stickers-app-7de9f.firebaseapp.com',
    storageBucket: 'whatsapp-stickers-app-7de9f.firebasestorage.app',
    measurementId: 'G-T7D09GK79C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-lpF7pK1K361srN2HlzGmXMxJp5TvAuc',
    appId: '1:263563615046:android:b6534cfa8371aa19356347',
    messagingSenderId: '263563615046',
    projectId: 'whatsapp-stickers-app-7de9f',
    storageBucket: 'whatsapp-stickers-app-7de9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4JgdJLn9lAb-yrA5CsVaZYG7WFp5hui8',
    appId: '1:263563615046:ios:83d3a976b8dd4f12356347',
    messagingSenderId: '263563615046',
    projectId: 'whatsapp-stickers-app-7de9f',
    storageBucket: 'whatsapp-stickers-app-7de9f.firebasestorage.app',
    androidClientId: '263563615046-cn54l0g1dcr6shjkih3t20lriuka79rs.apps.googleusercontent.com',
    iosClientId: '263563615046-qdbo85kd9n966o8b3po1hv3rfoi5ku4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappStickersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4JgdJLn9lAb-yrA5CsVaZYG7WFp5hui8',
    appId: '1:263563615046:ios:83d3a976b8dd4f12356347',
    messagingSenderId: '263563615046',
    projectId: 'whatsapp-stickers-app-7de9f',
    storageBucket: 'whatsapp-stickers-app-7de9f.firebasestorage.app',
    androidClientId: '263563615046-cn54l0g1dcr6shjkih3t20lriuka79rs.apps.googleusercontent.com',
    iosClientId: '263563615046-qdbo85kd9n966o8b3po1hv3rfoi5ku4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappStickersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO_LJdQO2rOqtlhP2yAdESC1PY1uvyJiE',
    appId: '1:263563615046:web:713d49e5afc4377d356347',
    messagingSenderId: '263563615046',
    projectId: 'whatsapp-stickers-app-7de9f',
    authDomain: 'whatsapp-stickers-app-7de9f.firebaseapp.com',
    storageBucket: 'whatsapp-stickers-app-7de9f.firebasestorage.app',
    measurementId: 'G-E58CPHTVKZ',
  );
}
